# Generated by Django 5.2.8 on 2025-11-27 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOverview', models.CharField(max_length=100)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('search_tags', models.CharField(blank=True, max_length=200)),
                ('location_lat', models.FloatField(default=27.7)),
                ('location_lng', models.FloatField(default=85.7)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('delivery_time', models.PositiveIntegerField(help_text='Days')),
                ('revisions', models.CharField(max_length=20)),
                ('source_file', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='services.overview')),
            ],
            options={
                'unique_together': {('overview', 'package_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings_received', to='services.overview')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esewa_id', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('choices', 'Multiple Choice')], default='text', max_length=20)),
                ('answer_text', models.TextField(blank=True)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.overview')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.overview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service', 'user')},
            },
        ),
    ]
