# Generated by Django 5.2.8 on 2025-11-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='location_lat',
            field=models.FloatField(default=27.7),
        ),
        migrations.AlterField(
            model_name='overview',
            name='location_lng',
            field=models.FloatField(default=85.7),
        ),
    ]
