# Generated by Django 5.2.8 on 2025-11-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240520_1817'),
        ('Services', '0002_auto_20240520_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('teacher', 'Teacher'), ('designer', 'Designer')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('availability', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Home.userprofile')),
            ],
        ),
    ]
