# Generated by Django 5.2.8 on 2025-11-10 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_ratingseller_review_rating_and_more'),
        ('Services', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpackage',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='standardpackage',
            name='overview',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='allow_multiple_selection',
            new_name='allow_multiple',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='Services.overview'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Services.overview'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='overview',
            name='search_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text="['Option 1', 'Option 2']"),
        ),
        migrations.AlterField(
            model_name='question',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Services.overview'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('choices', 'Multiple Choice')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='ratingservice',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='Services.overview'),
        ),
        migrations.AlterField(
            model_name='ratingservice',
            name='review_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingservice',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings_given', to='Home.userprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.JSONField(default=dict, help_text="e.g., {'2025-11-11': ['09:00', '14:00']}"),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('teacher', 'Teacher'), ('designer', 'Designer'), ('carpenter', 'Carpenter'), ('cleaner', 'Cleaner')], max_length=50),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('delivery_time', models.PositiveIntegerField(help_text='Days')),
                ('revisions', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), ('unlimited', 'Unlimited')], max_length=20)),
                ('source_file', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='Services.overview')),
            ],
            options={
                'unique_together': {('overview', 'package_type')},
            },
        ),
        migrations.DeleteModel(
            name='BasicPackage',
        ),
        migrations.DeleteModel(
            name='PremiumPackage',
        ),
        migrations.DeleteModel(
            name='StandardPackage',
        ),
    ]
