# Generated by Django 5.2.8 on 2025-11-10 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingseller',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Nepal', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='Home.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='Bagmati', max_length=50),
        ),
    ]
